#!/bin/sh

set -e

todays_date=$(date "+%Y-%m-%d")
sed -i '' -E "s/[0-9]{4}-[0-9]{2}-[0-9]{2}/$todays_date/" src/version.cr
git add src/version.cr
git tag "$todays_date"
git commit -m "Version $todays_date"

echo
echo "Bumped version to $todays_date"
echo "Here are the commits since the last tag"
echo

git log $(git describe --tags --abbrev=0)~..HEAD --oneline
